[database]
url = "" # Your Database URL Goes here

[Core]
main_url = "" # Main Listening Address
file_size_limit = "" # File Size Limit
front_end_url = "" # Front end URL Goes Here

[Object]
name = ""
endpoint = "" 
process = ""

[S3]
bucket = ""
root = ""
region = ""
endpoint = ""
access_key_id = ""
secret_access_key = ""