//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.4

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "v_collection")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub public_id: String,
    pub title: String,
    pub description: Option<String>,
    pub r#type: String,
    pub state: String,
    pub i_ds: Option<Json>,
    pub properties: Option<Json>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
